export const countries = [
  { name: "Afghanistan", code: "AF", currency: "AFN (؋)" },
  { name: "Albania", code: "AL", currency: "ALL (L)" },
  { name: "Algeria", code: "DZ", currency: "DZD (د.ج)" },
  { name: "Andorra", code: "AD", currency: "EUR (€)" },
  { name: "Angola", code: "AO", currency: "AOA (Kz)" },
  { name: "Argentina", code: "AR", currency: "ARS ($)" },
  { name: "Armenia", code: "AM", currency: "AMD (֏)" },
  { name: "Australia", code: "AU", currency: "AUD ($)" },
  { name: "Austria", code: "AT", currency: "EUR (€)" },
  { name: "Azerbaijan", code: "AZ", currency: "AZN (₼)" },
  { name: "Bahamas", code: "BS", currency: "BSD ($)" },
  { name: "Bahrain", code: "BH", currency: "BHD (.د.ب)" },
  { name: "Bangladesh", code: "BD", currency: "BDT (৳)" },
  { name: "Belarus", code: "BY", currency: "BYN (Br)" },
  { name: "Belgium", code: "BE", currency: "EUR (€)" },
  { name: "Belize", code: "BZ", currency: "BZD ($)" },
  { name: "Benin", code: "BJ", currency: "XOF (CFA)" },
  { name: "Bhutan", code: "BT", currency: "BTN (Nu)" },
  { name: "Bolivia", code: "BO", currency: "BOB (Bs.)" },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM (KM)" },
  { name: "Botswana", code: "BW", currency: "BWP (P)" },
  { name: "Brazil", code: "BR", currency: "BRL (R$)" },
  { name: "Brunei", code: "BN", currency: "BND ($)" },
  { name: "Bulgaria", code: "BG", currency: "BGN (лв)" },
  { name: "Burkina Faso", code: "BF", currency: "XOF (CFA)" },
  { name: "Burundi", code: "BI", currency: "BIF (FBu)" },
  { name: "Cambodia", code: "KH", currency: "KHR (៛)" },
  { name: "Cameroon", code: "CM", currency: "XAF (FCFA)" },
  { name: "Canada", code: "CA", currency: "CAD ($)" },
  { name: "Chile", code: "CL", currency: "CLP ($)" },
  { name: "China", code: "CN", currency: "CNY (¥)" },
  { name: "Colombia", code: "CO", currency: "COP ($)" },
  { name: "Costa Rica", code: "CR", currency: "CRC (₡)" },
  { name: "Croatia", code: "HR", currency: "EUR (€)" },
  { name: "Cuba", code: "CU", currency: "CUP (₱)" },
  { name: "Cyprus", code: "CY", currency: "EUR (€)" },
  { name: "Czech Republic", code: "CZ", currency: "CZK (Kč)" },
  { name: "Denmark", code: "DK", currency: "DKK (kr)" },
  { name: "Dominican Republic", code: "DO", currency: "DOP (RD$)" },
  { name: "Ecuador", code: "EC", currency: "USD ($)" },
  { name: "Egypt", code: "EG", currency: "EGP (£)" },
  { name: "El Salvador", code: "SV", currency: "USD ($)" },
  { name: "Estonia", code: "EE", currency: "EUR (€)" },
  { name: "Ethiopia", code: "ET", currency: "ETB (Br)" },
  { name: "Fiji", code: "FJ", currency: "FJD ($)" },
  { name: "Finland", code: "FI", currency: "EUR (€)" },
  { name: "France", code: "FR", currency: "EUR (€)" },
  { name: "Germany", code: "DE", currency: "EUR (€)" },
  { name: "Ghana", code: "GH", currency: "GHS (₵)" },
  { name: "Greece", code: "GR", currency: "EUR (€)" },
  { name: "Guatemala", code: "GT", currency: "GTQ (Q)" },
  { name: "Honduras", code: "HN", currency: "HNL (L)" },
  { name: "Hong Kong", code: "HK", currency: "HKD ($)" },
  { name: "Hungary", code: "HU", currency: "HUF (Ft)" },
  { name: "Iceland", code: "IS", currency: "ISK (kr)" },
  { name: "India", code: "IN", currency: "INR (₹)" },
  { name: "Indonesia", code: "ID", currency: "IDR (Rp)" },
  { name: "Iran", code: "IR", currency: "IRR (﷼)" },
  { name: "Iraq", code: "IQ", currency: "IQD (د.ع)" },
  { name: "Ireland", code: "IE", currency: "EUR (€)" },
  { name: "Israel", code: "IL", currency: "ILS (₪)" },
  { name: "Italy", code: "IT", currency: "EUR (€)" },
  { name: "Jamaica", code: "JM", currency: "JMD ($)" },
  { name: "Japan", code: "JP", currency: "JPY (¥)" },
  { name: "Jordan", code: "JO", currency: "JOD (د.ا)" },
  { name: "Kenya", code: "KE", currency: "KES (Sh)" },
  { name: "Kuwait", code: "KW", currency: "KWD (د.ك)" },
  { name: "Latvia", code: "LV", currency: "EUR (€)" },
  { name: "Lebanon", code: "LB", currency: "LBP (£)" },
  { name: "Lithuania", code: "LT", currency: "EUR (€)" },
  { name: "Luxembourg", code: "LU", currency: "EUR (€)" },
  { name: "Malaysia", code: "MY", currency: "MYR (RM)" },
  { name: "Maldives", code: "MV", currency: "MVR (Rf)" },
  { name: "Mexico", code: "MX", currency: "MXN ($)" },
  { name: "Monaco", code: "MC", currency: "EUR (€)" },
  { name: "Mongolia", code: "MN", currency: "MNT (₮)" },
  { name: "Morocco", code: "MA", currency: "MAD (د.م.)" },
  { name: "Nepal", code: "NP", currency: "NPR (₨)" },
  { name: "Netherlands", code: "NL", currency: "EUR (€)" },
  { name: "New Zealand", code: "NZ", currency: "NZD ($)" },
  { name: "Nigeria", code: "NG", currency: "NGN (₦)" },
  { name: "Norway", code: "NO", currency: "NOK (kr)" },
  { name: "Oman", code: "OM", currency: "OMR (﷼)" },
  { name: "Pakistan", code: "PK", currency: "PKR (₨)" },
  { name: "Philippines", code: "PH", currency: "PHP (₱)" },
  { name: "Poland", code: "PL", currency: "PLN (zł)" },
  { name: "Portugal", code: "PT", currency: "EUR (€)" },
  { name: "Qatar", code: "QA", currency: "QAR (﷼)" },
  { name: "Romania", code: "RO", currency: "RON (lei)" },
  { name: "Russia", code: "RU", currency: "RUB (₽)" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR (﷼)" },
  { name: "Singapore", code: "SG", currency: "SGD ($)" },
  { name: "South Africa", code: "ZA", currency: "ZAR (R)" },
  { name: "South Korea", code: "KR", currency: "KRW (₩)" },
  { name: "Spain", code: "ES", currency: "EUR (€)" },
  { name: "Sri Lanka", code: "LK", currency: "LKR (₨)" },
  { name: "Sweden", code: "SE", currency: "SEK (kr)" },
  { name: "Switzerland", code: "CH", currency: "CHF (Fr)" },
  { name: "Thailand", code: "TH", currency: "THB (฿)" },
  { name: "Turkey", code: "TR", currency: "TRY (₺)" },
  { name: "Ukraine", code: "UA", currency: "UAH (₴)" },
  { name: "United Arab Emirates", code: "AE", currency: "AED (د.إ)" },
  { name: "United Kingdom", code: "GB", currency: "GBP (£)" },
  { name: "United States", code: "US", currency: "USD ($)" },
  { name: "Vietnam", code: "VN", currency: "VND (₫)" },
  { name: "Zimbabwe", code: "ZW", currency: "ZWL ($)" },
];
